version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      # Persist data, media, and logs
      - ./data:/app/data
      - ./media:/app/media
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
      - ./backups:/app/backups
    environment:
      - DJANGO_SETTINGS_MODULE=AxeCollection.settings_production
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://localhost,http://127.0.0.1}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - axe_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - axe_network

networks:
  axe_network:
    driver: bridge

volumes:
  data:
  media:
  logs:
  staticfiles:
  backups: 