# Generated by Django 5.2.3 on 2025-06-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0002_rename_ebay_alias_contact_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_naj_member',
            field=models.BooleanField(default=False, verbose_name='Medlem i Nordic Axe Junkies'),
        ),
    ]
