# Generated by Django 5.2.3 on 2025-06-22 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0003_contact_is_naj_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manufacturer_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='axes.manufacturer')),
            ],
            options={
                'verbose_name': 'Tillverkarbild',
                'verbose_name_plural': 'Tillverkarbilder',
            },
        ),
    ]
