# Generated by Django 5.2.3 on 2025-06-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0004_manufacturerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('WEBSITE', 'Hemsida'), ('CATALOG', 'Katalog'), ('VIDEO', 'Video/Film'), ('ARTICLE', 'Artikel'), ('DOCUMENT', 'Dokument'), ('OTHER', 'Övrigt')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='axes.manufacturer')),
            ],
            options={
                'ordering': ['link_type', 'title'],
            },
        ),
    ]
