# Generated by Django 5.2.3 on 2025-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0005_manufacturerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='axe',
            name='status',
            field=models.CharField(choices=[('KÖPT', 'Köpt'), ('MOTTAGEN', 'Mottagen/Ägd')], default='KÖPT', max_length=10),
        ),
    ]
