# Generated by Django 5.2.3 on 2025-06-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0006_axe_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextAxeID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_id', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Nästa yx-ID',
                'verbose_name_plural': 'Nästa yx-ID',
            },
        ),
    ]
