# Generated by Django 5.2.3 on 2025-06-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0007_nextaxeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='axeimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
