# Generated by Django 5.2.3 on 2025-07-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0008_axeimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Namn på mallen, t.ex. 'Standard yxa'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Beskrivning av mallen', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Om mallen ska vara tillgänglig')),
                ('sort_order', models.IntegerField(default=0, help_text='Sorteringsordning i listor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Namn på måtttypen, t.ex. 'Bladlängd'", max_length=100, unique=True)),
                ('unit', models.CharField(help_text="Standardenhet för måtttypen, t.ex. 'mm'", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Beskrivning av måtttypen', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Om måtttypen ska vara tillgänglig')),
                ('sort_order', models.IntegerField(default=0, help_text='Sorteringsordning i listor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='axeimage',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='MeasurementTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, help_text='Sorteringsordning inom mallen')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='axes.measurementtemplate')),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axes.measurementtype')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('template', 'measurement_type')},
            },
        ),
    ]
