# Generated by Django 5.2.3 on 2025-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0009_measurementtemplate_measurementtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturerimage',
            options={'ordering': ['image_type', 'order'], 'verbose_name': 'Tillverkarbild', 'verbose_name_plural': 'Tillverkarbilder'},
        ),
        migrations.AddField(
            model_name='manufacturerimage',
            name='image_type',
            field=models.CharField(choices=[('STAMP', 'Stämpel'), ('OTHER', 'Övrig bild')], default='STAMP', help_text='Typ av bild', max_length=20),
        ),
        migrations.AddField(
            model_name='manufacturerimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sorteringsordning inom samma typ'),
        ),
    ]
