# Generated by Django 5.2.3 on 2025-07-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0010_alter_manufacturerimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='comment',
            new_name='information',
        ),
    ]
