# Generated by Django 5.2.3 on 2025-07-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0011_rename_manufacturer_comment_to_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Information'),
        ),
    ]
