# Generated by Django 5.2.3 on 2025-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0012_add_order_to_manufacturerlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturerlink',
            options={'ordering': ['link_type', 'order']},
        ),
        migrations.AddField(
            model_name='manufacturerlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sorteringsordning inom samma typ'),
        ),
    ]
