# Generated by Django 5.2.3 on 2025-07-15 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0013_add_order_field_to_manufacturerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='axe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='axes.axe'),
        ),
    ]
