# Generated by Django 5.2.3 on 2025-07-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0014_alter_transaction_axe'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 landskod, t.ex. 'SE' för Sverige", max_length=2, null=True),
        ),
    ]
