# Generated by Django 5.2.3 on 2025-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0015_contact_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_contacts_public', models.BooleanField(default=False, help_text='Om kontaktinformation ska visas för icke-inloggade användare', verbose_name='Visa kontakter publikt')),
                ('show_prices_public', models.BooleanField(default=True, help_text='Om priser ska visas för icke-inloggade användare', verbose_name='Visa priser publikt')),
                ('show_platforms_public', models.BooleanField(default=True, help_text='Om plattformar ska visas för icke-inloggade användare', verbose_name='Visa plattformar publikt')),
                ('show_only_received_axes_public', models.BooleanField(default=False, help_text='Om endast mottagna yxor ska visas i publika listor', verbose_name='Visa endast mottagna yxor publikt')),
                ('site_title', models.CharField(default='AxeCollection', help_text='Titel som visas i webbläsaren och på sidor', max_length=100, verbose_name='Sajttitel')),
                ('site_description', models.TextField(blank=True, help_text='Beskrivning av sajten för sökmotorer', null=True, verbose_name='Sajtbeskrivning')),
            ],
            options={
                'verbose_name': 'Inställning',
                'verbose_name_plural': 'Inställningar',
            },
        ),
    ]
