# Generated by Django 5.2.3 on 2025-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0016_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_axes_rows_private',
            field=models.PositiveIntegerField(default=50, help_text='Antal yxor som visas per sida för inloggade användare', verbose_name='Standardantal yxor (privat)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_axes_rows_public',
            field=models.PositiveIntegerField(default=20, help_text='Antal yxor som visas per sida för icke-inloggade användare', verbose_name='Standardantal yxor (publik)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_manufacturers_rows_private',
            field=models.PositiveIntegerField(default=50, help_text='Antal tillverkare som visas per sida för inloggade användare', verbose_name='Standardantal tillverkare (privat)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_manufacturers_rows_public',
            field=models.PositiveIntegerField(default=25, help_text='Antal tillverkare som visas per sida för icke-inloggade användare', verbose_name='Standardantal tillverkare (publik)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_transactions_rows_private',
            field=models.PositiveIntegerField(default=30, help_text='Antal transaktioner som visas per sida för inloggade användare', verbose_name='Standardantal transaktioner (privat)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_transactions_rows_public',
            field=models.PositiveIntegerField(default=15, help_text='Antal transaktioner som visas per sida för icke-inloggade användare', verbose_name='Standardantal transaktioner (publik)'),
        ),
    ]
