# Generated by Django 5.2.3 on 2025-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0017_settings_default_axes_rows_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_axes_rows_private',
            field=models.CharField(choices=[('10', '10 rader'), ('25', '25 rader'), ('50', '50 rader'), ('100', '100 rader'), ('-1', 'Alla rader')], default='50', help_text='Antal yxor som visas per sida för inloggade användare', max_length=10, verbose_name='Standardantal yxor (privat)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_axes_rows_public',
            field=models.CharField(choices=[('10', '10 rader'), ('25', '25 rader'), ('50', '50 rader'), ('100', '100 rader'), ('-1', 'Alla rader')], default='20', help_text='Antal yxor som visas per sida för icke-inloggade användare', max_length=10, verbose_name='Standardantal yxor (publik)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_manufacturers_rows_private',
            field=models.CharField(choices=[('10', '10 rader'), ('25', '25 rader'), ('50', '50 rader'), ('100', '100 rader'), ('-1', 'Alla rader')], default='50', help_text='Antal tillverkare som visas per sida för inloggade användare', max_length=10, verbose_name='Standardantal tillverkare (privat)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_manufacturers_rows_public',
            field=models.CharField(choices=[('10', '10 rader'), ('25', '25 rader'), ('50', '50 rader'), ('100', '100 rader'), ('-1', 'Alla rader')], default='25', help_text='Antal tillverkare som visas per sida för icke-inloggade användare', max_length=10, verbose_name='Standardantal tillverkare (publik)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_transactions_rows_private',
            field=models.CharField(choices=[('10', '10 rader'), ('25', '25 rader'), ('50', '50 rader'), ('100', '100 rader'), ('-1', 'Alla rader')], default='30', help_text='Antal transaktioner som visas per sida för inloggade användare', max_length=10, verbose_name='Standardantal transaktioner (privat)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_transactions_rows_public',
            field=models.CharField(choices=[('10', '10 rader'), ('25', '25 rader'), ('50', '50 rader'), ('100', '100 rader'), ('-1', 'Alla rader')], default='15', help_text='Antal transaktioner som visas per sida för icke-inloggade användare', max_length=10, verbose_name='Standardantal transaktioner (publik)'),
        ),
    ]
