# Generated by Django 5.2.3 on 2025-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0018_alter_settings_default_axes_rows_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='color_class',
            field=models.CharField(choices=[('bg-primary', 'Blå'), ('bg-info', 'Ljusblå'), ('bg-warning', 'Gul/Orange'), ('bg-secondary', 'Grå'), ('bg-dark', 'Mörkgrå'), ('bg-light', 'Ljusgrå'), ('bg-primary-subtle', 'Ljusare blå'), ('bg-info-subtle', 'Ljusare ljusblå'), ('bg-warning-subtle', 'Ljusare gul'), ('bg-secondary-subtle', 'Ljusare grå'), ('bg-dark-subtle', 'Ljusare mörkgrå'), ('bg-light-subtle', 'Ännu ljusare grå')], default='bg-primary', help_text='Välj färg för plattformens badge', max_length=20, verbose_name='Färg för badge'),
        ),
    ]
