# Generated by Django 5.2.3 on 2025-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0021_alter_platform_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='color_class',
            field=models.CharField(choices=[('bg-primary', 'Blå (Primary)'), ('bg-secondary', 'Grå (Secondary)'), ('bg-success', 'Grön (Success)'), ('bg-danger', 'Röd (Danger)'), ('bg-warning', 'Gul/Orange (Warning)'), ('bg-info', 'Ljusblå (Info)'), ('bg-light', 'Ljusgrå (Light)'), ('bg-dark', 'Mörkgrå (Dark)'), ('bg-primary-subtle', 'Ljusare blå'), ('bg-secondary-subtle', 'Ljusare grå'), ('bg-success-subtle', 'Ljusare grön'), ('bg-danger-subtle', 'Ljusare röd'), ('bg-warning-subtle', 'Ljusare gul'), ('bg-info-subtle', 'Ljusare ljusblå'), ('bg-light-subtle', 'Ännu ljusare grå'), ('bg-dark-subtle', 'Ljusare mörkgrå'), ('bg-gradient-primary', 'Blå gradient'), ('bg-gradient-secondary', 'Grå gradient'), ('bg-gradient-success', 'Grön gradient'), ('bg-gradient-danger', 'Röd gradient'), ('bg-gradient-warning', 'Gul gradient'), ('bg-gradient-info', 'Ljusblå gradient'), ('bg-gradient-light', 'Ljusgrå gradient'), ('bg-gradient-dark', 'Mörkgrå gradient')], default='bg-primary', help_text='Välj färg för plattformens badge', max_length=25, verbose_name='Färg för badge'),
        ),
    ]
