# Generated by Django 5.2.3 on 2025-07-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0023_alter_platform_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='color_class',
            field=models.CharField(choices=[('bg-primary', 'Blå (Primary)'), ('bg-secondary', 'Grå (Secondary)'), ('bg-success', 'Grön (Success)'), ('bg-danger', 'Röd (Danger)'), ('bg-warning', 'Gul/Orange (Warning)'), ('bg-info', 'Cyan (Info)'), ('bg-light', 'Ljusgrå (Light)'), ('bg-dark', 'Mörkgrå (Dark)'), ('bg-gray-100', 'Mycket ljusgrå'), ('bg-gray-200', 'Ljusgrå'), ('bg-gray-300', 'Grå'), ('bg-gray-400', 'Mellanljusgrå'), ('bg-gray-500', 'Mellangrå'), ('bg-gray-600', 'Mörkgrå'), ('bg-gray-700', 'Mörkare grå'), ('bg-gray-800', 'Mycket mörkgrå'), ('bg-gray-900', 'Nästan svart'), ('bg-white', 'Vit'), ('bg-black', 'Svart'), ('bg-body', 'Bakgrundsfärg'), ('bg-muted', 'Dämpad'), ('bg-primary-subtle', 'Ljusare blå'), ('bg-secondary-subtle', 'Ljusare grå'), ('bg-success-subtle', 'Ljusare grön'), ('bg-danger-subtle', 'Ljusare röd'), ('bg-warning-subtle', 'Ljusare gul'), ('bg-info-subtle', 'Ljusare cyan'), ('bg-light-subtle', 'Ännu ljusare grå'), ('bg-dark-subtle', 'Ljusare mörkgrå')], default='bg-primary', help_text='Välj färg för plattformens badge', max_length=25, verbose_name='Färg för badge'),
        ),
    ]
