# Generated by Django 5.2.3 on 2025-07-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0024_alter_platform_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='color_class',
            field=models.CharField(choices=[('bg-primary', 'Blå (Primary)'), ('bg-secondary', 'Grå (Secondary)'), ('bg-success', 'Grön (Success)'), ('bg-danger', 'Röd (Danger)'), ('bg-warning', 'Gul/Orange (Warning)'), ('bg-info', 'Cyan (Info)'), ('bg-light', 'Ljusgrå (Light)'), ('bg-dark', 'Mörkgrå (Dark)'), ('bg-primary-subtle', 'Ljusare blå'), ('bg-secondary-subtle', 'Ljusare grå'), ('bg-success-subtle', 'Ljusare grön'), ('bg-danger-subtle', 'Ljusare röd'), ('bg-warning-subtle', 'Ljusare gul'), ('bg-info-subtle', 'Ljusare cyan'), ('bg-light-subtle', 'Ännu ljusare grå'), ('bg-dark-subtle', 'Ljusare mörkgrå'), ('bg-body', 'Bakgrundsfärg'), ('bg-muted', 'Dämpad'), ('bg-white', 'Vit'), ('bg-black', 'Svart'), ('bg-primary bg-opacity-75', 'Blå 75% opacity'), ('bg-secondary bg-opacity-75', 'Grå 75% opacity'), ('bg-success bg-opacity-75', 'Grön 75% opacity'), ('bg-danger bg-opacity-75', 'Röd 75% opacity'), ('bg-warning bg-opacity-75', 'Gul 75% opacity'), ('bg-info bg-opacity-75', 'Cyan 75% opacity'), ('bg-light bg-opacity-75', 'Ljusgrå 75% opacity'), ('bg-dark bg-opacity-75', 'Mörkgrå 75% opacity'), ('bg-primary text-white', 'Blå med vit text'), ('bg-secondary text-white', 'Grå med vit text'), ('bg-success text-white', 'Grön med vit text'), ('bg-danger text-white', 'Röd med vit text'), ('bg-warning text-dark', 'Gul med mörk text'), ('bg-info text-dark', 'Cyan med mörk text'), ('bg-light text-dark', 'Ljusgrå med mörk text'), ('bg-dark text-white', 'Mörkgrå med vit text')], default='bg-primary', help_text='Välj färg för plattformens badge', max_length=30, verbose_name='Färg för badge'),
        ),
    ]
