# Generated by Django 5.2.3 on 2025-07-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0025_alter_platform_color_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='external_csrf_origins',
            field=models.TextField(blank=True, help_text='Komma-separerad lista av CSRF-tillåtna origins med protokoll (t.ex. https://demo.domain.com,http://192.168.1.100)', null=True, verbose_name='CSRF-tillåtna origins'),
        ),
        migrations.AddField(
            model_name='settings',
            name='external_hosts',
            field=models.TextField(blank=True, help_text='Komma-separerad lista av externa hosts (t.ex. demo.domain.com,192.168.1.100)', null=True, verbose_name='Externa hosts'),
        ),
    ]
