# Generated by Django 5.2.3 on 2025-07-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0026_add_external_hosts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Tillverkare', 'verbose_name_plural': 'Tillverkare'},
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Välj en överordnad tillverkare om detta är en undertillverkare/smed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_manufacturers', to='axes.manufacturer', verbose_name='Överordnad tillverkare'),
        ),
    ]
