# Generated by Django 5.2.3 on 2025-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0027_alter_manufacturer_options_manufacturer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='manufacturer_type',
            field=models.CharField(choices=[('FABRIK', 'Fabrik'), ('SMED', 'Enskild smed')], default='FABRIK', help_text='Är detta en fabrik eller en enskild smed?', max_length=10, verbose_name='Typ av tillverkare'),
        ),
    ]
