# Generated by Django 5.2.3 on 2025-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0028_manufacturer_manufacturer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_type',
            field=models.CharField(choices=[('TILLVERKARE', 'Tillverkare'), ('SMED', 'Smed')], default='TILLVERKARE', help_text='Är detta en fabrik, smedja, bruk eller annan tillverkare - eller en enskild smed?', max_length=15, verbose_name='Typ av tillverkare'),
        ),
    ]
