# Generated by Django 5.2.3 on 2025-07-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0029_update_manufacturer_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='axeimage',
            name='cache_busting_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manufacturerimage',
            name='cache_busting_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
