# Generated by Django 5.2.3 on 2025-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0030_axeimage_cache_busting_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 landskod, t.ex. 'SE' för Sverige", max_length=2, null=True),
        ),
    ]
