# Generated by Django 5.2.3 on 2025-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0031_add_country_code_to_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='comment',
            field=models.TextField(blank=True, help_text='Beskrivning av plattformen', null=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='platform',
            name='url',
            field=models.URLField(blank=True, help_text='Hemsida för plattformen', null=True, verbose_name='URL'),
        ),
    ]
