# Generated by Django 5.2.3 on 2025-07-29 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0032_platform_comment_platform_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StampTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Namn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beskrivning')),
                ('color', models.CharField(default='#007bff', help_text='Hex-färg för taggen, t.ex. #007bff', max_length=7, verbose_name='Färg (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stämpeltagg',
                'verbose_name_plural': 'Stämpeltaggar',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='external_csrf_origins',
            field=models.TextField(blank=True, help_text='Komma-separerad lista av externa CSRF origins (t.ex. https://demo.domain.com,https://192.168.1.100)', null=True, verbose_name='Externa CSRF origins'),
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beskrivning')),
                ('stamp_type', models.CharField(choices=[('text', 'Text'), ('image', 'Bild'), ('symbol', 'Symbol')], default='text', max_length=20, verbose_name='Typ')),
                ('status', models.CharField(choices=[('known', 'Känd'), ('unknown', 'Okänd')], default='unknown', max_length=20, verbose_name='Status')),
                ('year_from', models.IntegerField(blank=True, null=True, verbose_name='Från år')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='Till år')),
                ('year_uncertainty', models.BooleanField(default=False, verbose_name='Osäker årtalsinformation')),
                ('year_notes', models.TextField(blank=True, null=True, verbose_name='Anteckningar om årtal')),
                ('source_category', models.CharField(choices=[('own_collection', 'Egen samling'), ('ebay_auction', 'eBay/Auktion'), ('museum', 'Museum'), ('private_collector', 'Privat samlare'), ('book_article', 'Bok/Artikel'), ('internet', 'Internet'), ('unknown', 'Okänd')], default='own_collection', max_length=20, verbose_name='Källkategori')),
                ('source_reference', models.TextField(blank=True, null=True, verbose_name='Källhänvisning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='axes.manufacturer', verbose_name='Tillverkare')),
            ],
            options={
                'verbose_name': 'Stämpel',
                'verbose_name_plural': 'Stämplar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StampImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stamps/', verbose_name='Bild')),
                ('quality', models.CharField(choices=[('high', 'Hög'), ('medium', 'Medium'), ('low', 'Låg')], default='medium', max_length=20, verbose_name='Kvalitet')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='axes.stamp', verbose_name='Stämpel')),
            ],
            options={
                'verbose_name': 'Stämpelbild',
                'verbose_name_plural': 'Stämpelbilder',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StampTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('quality', models.CharField(choices=[('high', 'Hög'), ('medium', 'Medium'), ('low', 'Låg')], default='medium', max_length=20, verbose_name='Kvalitet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='axes.stamp', verbose_name='Stämpel')),
            ],
            options={
                'verbose_name': 'Stämpeltranskribering',
                'verbose_name_plural': 'Stämpeltranskriberingar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StampUncertaintyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Namn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beskrivning')),
                ('confidence_level', models.CharField(choices=[('high', 'Hög'), ('medium', 'Medium'), ('low', 'Låg')], default='medium', max_length=20, verbose_name='Konfidensnivå')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stamps', models.ManyToManyField(related_name='uncertainty_groups', to='axes.stamp', verbose_name='Stämplar')),
            ],
            options={
                'verbose_name': 'Osäkerhetsgrupp',
                'verbose_name_plural': 'Osäkerhetsgrupper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AxeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('position', models.CharField(blank=True, help_text='Var på yxan stämpeln finns', max_length=100, null=True, verbose_name='Position')),
                ('uncertainty_level', models.CharField(choices=[('certain', 'Säker'), ('uncertain', 'Osäker'), ('tentative', 'Tentativ')], default='certain', max_length=20, verbose_name='Osäkerhetsnivå')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='axes.axe', verbose_name='Yxa')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='axes.stamp', verbose_name='Stämpel')),
            ],
            options={
                'verbose_name': 'Yxstämpel',
                'verbose_name_plural': 'Yxstämplar',
                'ordering': ['-created_at'],
                'unique_together': {('axe', 'stamp')},
            },
        ),
        migrations.CreateModel(
            name='StampVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Beskrivning av skillnaden', null=True, verbose_name='Beskrivning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='axes.stamp', verbose_name='Huvudstämpel')),
                ('variant_stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_stamp', to='axes.stamp', verbose_name='Variantstämpel')),
            ],
            options={
                'verbose_name': 'Stämpelvariant',
                'verbose_name_plural': 'Stämpelvarianter',
                'ordering': ['-created_at'],
                'unique_together': {('main_stamp', 'variant_stamp')},
            },
        ),
    ]
