# Generated by Django 5.2.3 on 2025-07-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0033_stamptag_alter_settings_external_csrf_origins_stamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stampimage',
            options={'ordering': ['order', '-uploaded_at'], 'verbose_name': 'Stämpelbild', 'verbose_name_plural': 'Stämpelbilder'},
        ),
        migrations.AddField(
            model_name='stampimage',
            name='cache_busting_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Cache-busting timestamp'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Kort beskrivning av bilden', max_length=255, null=True, verbose_name='Bildtext'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='description',
            field=models.TextField(blank=True, help_text='Detaljerad beskrivning av vad bilden visar', null=True, verbose_name='Beskrivning'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sorteringsordning för bilderna', verbose_name='Ordning'),
        ),
    ]
