# Generated by Django 5.2.3 on 2025-07-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0034_alter_stampimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='stamp_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Bild'), ('symbol', 'Symbol'), ('label', 'Etikett')], default='text', max_length=20, verbose_name='Typ'),
        ),
    ]
