# Generated by Django 5.2.3 on 2025-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0035_alter_stamp_stamp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='stamp_type',
            field=models.CharField(choices=[('text', 'Text'), ('symbol', 'Symbol'), ('text_symbol', 'Text + Symbol'), ('label', 'Etikett')], default='text', max_length=20, verbose_name='Typ'),
        ),
    ]
