# Generated by Django 5.2.3 on 2025-07-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0036_alter_stamp_stamp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeImageStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.PositiveIntegerField(blank=True, help_text='X-koordinat för stämpelområdet (pixlar från vänster)', null=True, verbose_name='X-koordinat')),
                ('y_coordinate', models.PositiveIntegerField(blank=True, help_text='Y-koordinat för stämpelområdet (pixlar från toppen)', null=True, verbose_name='Y-koordinat')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Bredd på stämpelområdet (pixlar)', null=True, verbose_name='Bredd')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Höjd på stämpelområdet (pixlar)', null=True, verbose_name='Höjd')),
                ('show_full_image', models.BooleanField(default=False, help_text='Visa hela yxbilden istället för bara stämpelområdet', verbose_name='Visa hela bilden')),
                ('is_primary', models.BooleanField(default=False, help_text='Markera som huvudbild för stämpeln', verbose_name='Huvudbild')),
                ('comment', models.TextField(blank=True, help_text='Anteckningar om stämpelområdet', null=True, verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_marks', to='axes.axeimage', verbose_name='Yxbild')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axe_image_marks', to='axes.stamp', verbose_name='Stämpel')),
            ],
            options={
                'verbose_name': 'Yxbildstämpel',
                'verbose_name_plural': 'Yxbildstämplar',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('axe_image', 'stamp')},
            },
        ),
    ]
