# Generated by Django 5.2.3 on 2025-07-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0037_axeimagestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='axestamp',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='axestamp',
            name='uncertainty_level',
            field=models.CharField(choices=[('certain', 'Säker'), ('uncertain', 'Osäker'), ('tentative', 'Preliminär')], default='certain', max_length=20, verbose_name='Osäkerhetsnivå'),
        ),
    ]
