# Generated by Django 5.2.3 on 2025-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0039_remove_axeimagestamp_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Höjd på stämpelområdet (pixlar)', null=True, verbose_name='Höjd'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Markera som huvudbild för stämpeln', verbose_name='Huvudbild'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Bredd på stämpelområdet (pixlar)', null=True, verbose_name='Bredd'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='x_coordinate',
            field=models.PositiveIntegerField(blank=True, help_text='X-koordinat för stämpelområdet (pixlar från vänster)', null=True, verbose_name='X-koordinat'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='y_coordinate',
            field=models.PositiveIntegerField(blank=True, help_text='Y-koordinat för stämpelområdet (pixlar från toppen)', null=True, verbose_name='Y-koordinat'),
        ),
    ]
