# Generated by Django 5.2.3 on 2025-07-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0040_stampimage_height_stampimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampimage',
            name='comment',
            field=models.TextField(blank=True, help_text='Anteckningar om stämpelområdet', null=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='position',
            field=models.CharField(blank=True, help_text='Var på bilden stämpeln finns', max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='uncertainty_level',
            field=models.CharField(choices=[('certain', 'Säker'), ('uncertain', 'Osäker'), ('tentative', 'Preliminär')], default='certain', max_length=20, verbose_name='Osäkerhetsnivå'),
        ),
    ]
