# Generated by Django 5.2.3 on 2025-07-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0041_stampimage_comment_stampimage_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='axeimagestamp',
            name='position',
            field=models.CharField(blank=True, help_text='Var på yxan stämpeln finns', max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='axeimagestamp',
            name='uncertainty_level',
            field=models.CharField(choices=[('certain', 'Säker'), ('uncertain', 'Osäker'), ('tentative', 'Preliminär')], default='certain', max_length=20, verbose_name='Osäkerhetsnivå'),
        ),
    ]
