# Generated by Django 5.2.3 on 2025-07-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0042_axeimagestamp_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stampimage',
            name='quality',
        ),
        migrations.AddField(
            model_name='stampimage',
            name='axe_image',
            field=models.ForeignKey(blank=True, help_text='Koppling till yxbild om detta är en markering', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stamp_markings', to='axes.axeimage', verbose_name='Yxbild'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='external_source',
            field=models.CharField(blank=True, help_text="Källa för extern bild (t.ex. 'Museum X', 'Bok Y')", max_length=200, null=True, verbose_name='Extern källa'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='image_type',
            field=models.CharField(choices=[('standalone', 'Fristående stämpelbild'), ('axe_mark', 'Yxbildmarkering'), ('reference', 'Referensbild'), ('documentation', 'Dokumentationsbild')], default='standalone', max_length=20, verbose_name='Bildtyp'),
        ),
        migrations.AddField(
            model_name='stampimage',
            name='show_full_image',
            field=models.BooleanField(default=False, help_text='Visa hela yxbilden istället för bara stämpelområdet', verbose_name='Visa hela bilden'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Höjd på stämpelområdet (procent av bildhöjd)', max_digits=5, null=True, verbose_name='Höjd (%)'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='position',
            field=models.CharField(blank=True, help_text="Var på bilden/yxan stämpeln finns (t.ex. 'på bladet - vänstra sidan')", max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bredd på stämpelområdet (procent av bildbredd)', max_digits=5, null=True, verbose_name='Bredd (%)'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='x_coordinate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='X-koordinat för stämpelområdet (procent från vänster)', max_digits=5, null=True, verbose_name='X-koordinat (%)'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='y_coordinate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Y-koordinat för stämpelområdet (procent från toppen)', max_digits=5, null=True, verbose_name='Y-koordinat (%)'),
        ),
        migrations.DeleteModel(
            name='AxeImageStamp',
        ),
    ]
