# Generated by Django 5.2.3 on 2025-07-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0043_consolidate_stamp_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Namn')),
                ('symbol_type', models.CharField(choices=[('crown', 'Krona'), ('cannon', 'Kanon'), ('star', 'Stjärna'), ('cross', 'Kors'), ('shield', 'Sköld'), ('anchor', 'Ankare'), ('flower', 'Blomma'), ('leaf', 'Löv'), ('other', 'Övrigt')], default='other', max_length=20, verbose_name='Symboltyp')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beskrivning')),
                ('is_predefined', models.BooleanField(default=False, help_text='Om symbolen är fördefinierad eller skapad av användare', verbose_name='Fördefinierad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stämpelsymbol',
                'verbose_name_plural': 'Stämpelsymboler',
                'ordering': ['symbol_type', 'name'],
                'unique_together': {('name', 'symbol_type')},
            },
        ),
    ]
