# Generated by Django 5.2.3 on 2025-07-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0044_stampsymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamptranscription',
            name='symbols',
            field=models.ManyToManyField(blank=True, help_text='Symboler som förekommer i denna transkribering', to='axes.stampsymbol', verbose_name='Symboler'),
        ),
    ]
