# Generated by Django 5.2.3 on 2025-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0045_stamptranscription_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampsymbol',
            name='pictogram',
            field=models.CharField(blank=True, help_text='Unicode-piktogram för symbolen (t.ex. 👑 för Krona, ⭕ för Cirkel)', max_length=10, null=True, verbose_name='Piktogram'),
        ),
        migrations.AlterField(
            model_name='stampsymbol',
            name='symbol_type',
            field=models.CharField(choices=[('crown', 'Krona'), ('cannon', 'Kanon'), ('star', 'Stjärna'), ('cross', 'Kors'), ('shield', 'Sköld'), ('anchor', 'Ankare'), ('flower', 'Blomma'), ('leaf', 'Löv'), ('arrow', 'Pil'), ('circle', 'Cirkel'), ('square', 'Fyrkant'), ('triangle', 'Triangel'), ('diamond', 'Diamant'), ('heart', 'Hjärta'), ('other', 'Övrigt')], default='other', max_length=20, verbose_name='Symboltyp'),
        ),
    ]
