# Generated by Django 5.2.3 on 2025-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0047_create_predefined_stamp_symbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamptranscription',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
