# Generated by Django 5.2.3 on 2025-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0048_change_text_field_to_textarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='axestamp',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Yxstämpel', 'verbose_name_plural': 'Yxstämplar'},
        ),
        migrations.AlterModelOptions(
            name='stamptranscription',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Stämpeltranskribering', 'verbose_name_plural': 'Stämpeltranskriberingar'},
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='stamp_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Bild'), ('symbol', 'Symbol'), ('text_symbol', 'Text + Symbol'), ('label', 'Etikett')], default='text', max_length=20, verbose_name='Typ'),
        ),
    ]
