# Generated by Django 5.2.3 on 2025-08-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0049_add_country_website_to_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampimage',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Höjd på stämpelområdet (procent av bildhöjd)', max_digits=9, null=True, verbose_name='Höjd (%)'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Bredd på stämpelområdet (procent av bildbredd)', max_digits=9, null=True, verbose_name='Bredd (%)'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='x_coordinate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='X-koordinat för stämpelområdet (procent från vänster)', max_digits=9, null=True, verbose_name='X-koordinat (%)'),
        ),
        migrations.AlterField(
            model_name='stampimage',
            name='y_coordinate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Y-koordinat för stämpelområdet (procent från toppen)', max_digits=9, null=True, verbose_name='Y-koordinat (%)'),
        ),
    ]
