# Generated by Django 5.2.3 on 2025-08-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0050_relax_stampimage_requirements_and_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Namn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beskrivning')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sorteringsordning')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Symbolkategori',
                'verbose_name_plural': 'Symbolkategorier',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='stampuncertaintygroup',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Osäkerhetsgrupp', 'verbose_name_plural': 'Osäkerhetsgrupper'},
        ),
    ]
