# Generated by Django 5.2.3 on 2025-08-10 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0051_symbolcategory_alter_stampuncertaintygroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampsymbol',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbols', to='axes.symbolcategory', verbose_name='Kategori'),
        ),
    ]
