# Generated by Django 5.2.3 on 2025-08-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0052_stampsymbol_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamptranscription',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
