# Generated by Django 5.2.3 on 2026-07-21 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axes", "0053_alter_stamptranscription_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Skapad"),
                            ("UPDATE", "Ändrad"),
                            ("DELETE", "Borttagen"),
                        ],
                        max_length=10,
                        verbose_name="Åtgärd",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modell")),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="Objekt-ID"),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=255, verbose_name="Objektbeskrivning"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ändringar"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Användare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ändringslogg",
                "verbose_name_plural": "Ändringsloggar",
                "ordering": ["-timestamp"],
            },
        ),
    ]
