# Generated by Django 5.2.3 on 2026-07-23 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0054_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='comments_enabled_public',
            field=models.BooleanField(default=True, help_text='Om anonyma besökare får skicka in kommentarer på yxor och tillverkare', verbose_name='Tillåt publika kommentarer'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=80, verbose_name='Namn')),
                ('body', models.TextField(max_length=2000, verbose_name='Kommentar')),
                ('status', models.CharField(choices=[('PENDING', 'Väntar'), ('APPROVED', 'Godkänd'), ('REJECTED', 'Avvisad'), ('SPAM', 'Skräp')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('axe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='axes.axe')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='axes.manufacturer')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentarer',
                'ordering': ['-created_at'],
            },
        ),
    ]
