# Generated by Django 5.2.3 on 2026-07-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0055_settings_comments_enabled_public_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='axes.stamp'),
        ),
    ]
