# Generated by Django 5.2.3 on 2026-07-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axes", "0056_comment_stamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="depth",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_removed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replies",
                to="axes.comment",
            ),
        ),
    ]
