# Generated by Django 5.2.3 on 2026-07-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0057_comment_depth_comment_is_removed_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ntfy_topic_url',
            field=models.URLField(blank=True, default='', help_text='Topic-URL för push-notiser (t.ex. https://ntfy.sh/mitt-topic). Tom = notiser avstängda.', verbose_name='ntfy.sh topic-URL'),
        ),
    ]
