# Generated by Django 5.2.3 on 2026-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0058_settings_ntfy_topic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='ntfy_token',
            field=models.CharField(blank=True, default='', help_text='Bearer-token (tk_...) för skyddade topics på egen ntfy-server. Tom = ingen auth-header (öppna topics).', max_length=255, verbose_name='ntfy.sh access-token'),
        ),
    ]
