name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    
    - name: Run linting
      run: |
        python -m flake8 axes/ --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 axes/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Run code formatting check
      run: |
        python -m black --check axes/
    
    - name: Run tests with coverage
      env:
        DJANGO_SETTINGS_MODULE: AxeCollection.settings
      run: |
        python manage.py collectstatic --noinput
        python manage.py migrate
        python -m coverage run --source='.' manage.py test
        python -m coverage report
        python -m coverage xml
        python -m coverage html
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run security checks
      run: |
        # Install security tools
        pip install bandit safety
        
        # Run bandit security checks
        bandit -r axes/ -f json -o bandit-report.json || true
        
        # Run safety checks for known vulnerabilities
        safety check --json --output safety-report.json || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t axecollection:latest .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker tag axecollection:latest ${{ secrets.DOCKER_USERNAME }}/axecollection:latest
        docker tag axecollection:latest ${{ secrets.DOCKER_USERNAME }}/axecollection:unraid
        docker push ${{ secrets.DOCKER_USERNAME }}/axecollection:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/axecollection:unraid 